//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrphanHousingService.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrphanHousingService.Resources.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distributed.
        /// </summary>
        public static string ApartmentStatus_Distributed {
            get {
                return ResourceManager.GetString("ApartmentStatus_Distributed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Excluded.
        /// </summary>
        public static string ApartmentStatus_Excluded {
            get {
                return ResourceManager.GetString("ApartmentStatus_Excluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Free.
        /// </summary>
        public static string ApartmentStatus_Free {
            get {
                return ResourceManager.GetString("ApartmentStatus_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на InSpecialFund.
        /// </summary>
        public static string ApartmentStatus_InSpecialFund {
            get {
                return ResourceManager.GetString("ApartmentStatus_InSpecialFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SocialRent.
        /// </summary>
        public static string ApartmentStatus_SocialRent {
            get {
                return ResourceManager.GetString("ApartmentStatus_SocialRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Approved.
        /// </summary>
        public static string ApplicationStatus_Approved {
            get {
                return ResourceManager.GetString("ApplicationStatus_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pending.
        /// </summary>
        public static string ApplicationStatus_Pending {
            get {
                return ResourceManager.GetString("ApplicationStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rejected.
        /// </summary>
        public static string ApplicationStatus_Rejected {
            get {
                return ResourceManager.GetString("ApplicationStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ContractReduction.
        /// </summary>
        public static string ApplicationType_ContractReduction {
            get {
                return ResourceManager.GetString("ApplicationType_ContractReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extension.
        /// </summary>
        public static string ApplicationType_Extension {
            get {
                return ResourceManager.GetString("ApplicationType_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SocialRentTransfer.
        /// </summary>
        public static string ApplicationType_SocialRentTransfer {
            get {
                return ResourceManager.GetString("ApplicationType_SocialRentTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Active.
        /// </summary>
        public static string ContractStatus_Active {
            get {
                return ResourceManager.GetString("ContractStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expired.
        /// </summary>
        public static string ContractStatus_Expired {
            get {
                return ResourceManager.GetString("ContractStatus_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Terminated.
        /// </summary>
        public static string ContractStatus_Terminated {
            get {
                return ResourceManager.GetString("ContractStatus_Terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RepeatedSpecializedRent.
        /// </summary>
        public static string ContractType_RepeatedSpecializedRent {
            get {
                return ResourceManager.GetString("ContractType_RepeatedSpecializedRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SocialRent.
        /// </summary>
        public static string ContractType_SocialRent {
            get {
                return ResourceManager.GetString("ContractType_SocialRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SpecializedRent.
        /// </summary>
        public static string ContractType_SpecializedRent {
            get {
                return ResourceManager.GetString("ContractType_SpecializedRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Approved.
        /// </summary>
        public static string DecisionResult_Approved {
            get {
                return ResourceManager.GetString("DecisionResult_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rejected.
        /// </summary>
        public static string DecisionResult_Rejected {
            get {
                return ResourceManager.GetString("DecisionResult_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ContractReduction.
        /// </summary>
        public static string DecisionType_ContractReduction {
            get {
                return ResourceManager.GetString("DecisionType_ContractReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distribution.
        /// </summary>
        public static string DecisionType_Distribution {
            get {
                return ResourceManager.GetString("DecisionType_Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ExclusionFromFund.
        /// </summary>
        public static string DecisionType_ExclusionFromFund {
            get {
                return ResourceManager.GetString("DecisionType_ExclusionFromFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extension.
        /// </summary>
        public static string DecisionType_Extension {
            get {
                return ResourceManager.GetString("DecisionType_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refusal.
        /// </summary>
        public static string DecisionType_Refusal {
            get {
                return ResourceManager.GetString("DecisionType_Refusal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SocialRentTransfer.
        /// </summary>
        public static string DecisionType_SocialRentTransfer {
            get {
                return ResourceManager.GetString("DecisionType_SocialRentTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paid.
        /// </summary>
        public static string UtilityDebtStatus_Paid {
            get {
                return ResourceManager.GetString("UtilityDebtStatus_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unpaid.
        /// </summary>
        public static string UtilityDebtStatus_Unpaid {
            get {
                return ResourceManager.GetString("UtilityDebtStatus_Unpaid", resourceCulture);
            }
        }
    }
}
